apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd  
spec:
  project: monitoring  
  source:
    helm:
      chart: grafana/grafana
      version: 8.0.6 
      values: |
        persistence:
          enabled: true
          storageClassName: default
          size: 10Gi

   
  destination:
    server: https://kubernetes.default.svc  
    namespace: monitoring 
  syncPolicy:
    automated:
      prune: true  
    syncOptions:
      - CreateNamespace=true  
