apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd 
spec:
  project: monitoring  
  source:
    helm:
      chart: prometheus-community/prometheus
      version: 16.2.4 
      values: |
        server:
          retention: "24h"
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 10Gi
        alertmanager:
          enabled: true
          nodeSelector:
            kubernetes.io/os: linux
  destination:
    server: https://kubernetes.default.svc  
    namespace: monitoring  
  syncPolicy:
    automated:
      prune: true 
    syncOptions:
      - CreateNamespace=true  