apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd 
spec:
  project: infra-apps
  source:
    helm:
      chart: argo/argocd-image-updater
      version: 1.4.3  
      values: |
        imageUpdater:
          enabled: true
          checkInterval: 60m
          logLevel: info
  destination:
    server: https://kubernetes.default.svc  
    namespace: argocd 
  syncPolicy:
    automated:
      prune: true 
    syncOptions:
      - CreateNamespace=true  